server:
  port: 8080
spring:
  application:
    name: ticketmanager
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/smartticketdb?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true
    username: root
    password: Dimosha1997
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: U2FsdGVkX1+FiYe3o7y2vT8i5/3rxlXyFzdxBbw1UUM=
  expiration: 86400000