server:
  port: 8080
spring:
  application:
    name: ticketmanager
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/smartticketdb?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true
    username: root
    password: Dimosha1997
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h in millisecond
    expiration-time: 3600000